namespace MTA.Domain.Entities;

/// <summary>
/// Base entity class that provides common properties for all entities in the MTA system.
/// This abstract class implements the common audit fields and primary key pattern
/// used across all domain entities.
/// </summary>
/// <remarks>
/// All domain entities should inherit from this base class to ensure consistency
/// in primary key naming and audit trail functionality. The Id property serves
/// as the primary key for all entities, while CreatedAt and UpdatedAt provide
/// automatic audit trail capabilities.
/// </remarks>
public abstract class BaseEntity
{
    /// <summary>
    /// Gets or sets the unique identifier for the entity.
    /// This serves as the primary key for all entities in the system.
    /// </summary>
    /// <value>
    /// An integer value that uniquely identifies the entity within its table.
    /// This value is typically auto-generated by the database.
    /// </value>
    public int Id { get; set; }
    
    /// <summary>
    /// Gets or sets the date and time when the entity was created.
    /// This property is automatically set to the current UTC time when the entity is instantiated.
    /// </summary>
    /// <value>
    /// A DateTime value representing when the entity was first created in the system.
    /// This value should not be modified after the entity is created.
    /// </value>
    /// <remarks>
    /// This property is part of the audit trail and helps track when records were added to the system.
    /// The default value is set to DateTime.UtcNow to ensure consistency across different time zones.
    /// </remarks>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// Gets or sets the date and time when the entity was last updated.
    /// This property should be set whenever the entity is modified.
    /// </summary>
    /// <value>
    /// A nullable DateTime value representing the last modification time.
    /// Null indicates the entity has never been updated since creation.
    /// </value>
    /// <remarks>
    /// This property is part of the audit trail and helps track when records were last modified.
    /// It should be updated automatically by the repository or service layer when changes are made.
    /// </remarks>
    public DateTime? UpdatedAt { get; set; }
}
