// <auto-generated />
using System;
using MTA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTA.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250823075447_UpdateTables")]
    partial class UpdateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTA.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageIcon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Poster")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("StatusId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MTA.Domain.Entities.FAQCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FAQCategories");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3155),
                            Title = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3156),
                            Title = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3157),
                            Title = "Advanced"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3158),
                            Title = "Professional"
                        });
                });

            modelBuilder.Entity("MTA.Domain.Entities.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Key")
                        .IsUnique();

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "AccountStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2821),
                            Key = "Active",
                            Value = "فعال"
                        },
                        new
                        {
                            Id = 2,
                            Category = "AccountStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2825),
                            Key = "Inactive",
                            Value = "غیرفعال"
                        },
                        new
                        {
                            Id = 3,
                            Category = "AccountStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2826),
                            Key = "Suspended",
                            Value = "مسدود"
                        },
                        new
                        {
                            Id = 4,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2827),
                            Key = "Draft",
                            Value = "پیش‌نویس"
                        },
                        new
                        {
                            Id = 5,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2828),
                            Key = "Published",
                            Value = "منتشر شده"
                        },
                        new
                        {
                            Id = 6,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2828),
                            Key = "Archived",
                            Value = "بایگانی"
                        },
                        new
                        {
                            Id = 7,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2829),
                            Key = "Suspended",
                            Value = "معلق"
                        },
                        new
                        {
                            Id = 8,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2830),
                            Key = "Retired",
                            Value = "منقضی شده"
                        },
                        new
                        {
                            Id = 9,
                            Category = "MediaType",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2831),
                            Key = "Video",
                            Value = "ویدئو"
                        },
                        new
                        {
                            Id = 10,
                            Category = "MediaType",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2832),
                            Key = "Document",
                            Value = "سند"
                        },
                        new
                        {
                            Id = 11,
                            Category = "MediaType",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2832),
                            Key = "Image",
                            Value = "تصویر"
                        },
                        new
                        {
                            Id = 12,
                            Category = "MediaType",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2833),
                            Key = "Audio",
                            Value = "صوت"
                        },
                        new
                        {
                            Id = 13,
                            Category = "DurationUnit",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2834),
                            Key = "Day",
                            Value = "روز"
                        },
                        new
                        {
                            Id = 14,
                            Category = "DurationUnit",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2835),
                            Key = "Week",
                            Value = "هفته"
                        },
                        new
                        {
                            Id = 15,
                            Category = "DurationUnit",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2909),
                            Key = "Month",
                            Value = "ماه"
                        },
                        new
                        {
                            Id = 16,
                            Category = "FAQCategory",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2910),
                            Key = "General",
                            Value = "عمومی"
                        },
                        new
                        {
                            Id = 17,
                            Category = "FAQCategory",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2911),
                            Key = "Payment",
                            Value = "پرداخت"
                        },
                        new
                        {
                            Id = 18,
                            Category = "FAQCategory",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2912),
                            Key = "Technical",
                            Value = "فنی"
                        },
                        new
                        {
                            Id = 19,
                            Category = "FAQCategory",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2913),
                            Key = "Course",
                            Value = "دوره‌ها"
                        },
                        new
                        {
                            Id = 20,
                            Category = "TicketStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2913),
                            Key = "Open",
                            Value = "باز"
                        },
                        new
                        {
                            Id = 21,
                            Category = "TicketStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2914),
                            Key = "Pending",
                            Value = "در انتظار"
                        },
                        new
                        {
                            Id = 22,
                            Category = "TicketStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2915),
                            Key = "Closed",
                            Value = "بسته شده"
                        },
                        new
                        {
                            Id = 23,
                            Category = "PackageStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2916),
                            Key = "Active",
                            Value = "فعال"
                        },
                        new
                        {
                            Id = 24,
                            Category = "PackageStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2917),
                            Key = "Expired",
                            Value = "منقضی"
                        },
                        new
                        {
                            Id = 25,
                            Category = "PackageStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2917),
                            Key = "Pending",
                            Value = "در انتظار"
                        },
                        new
                        {
                            Id = 26,
                            Category = "UserCourseStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2918),
                            Key = "Active",
                            Value = "فعال"
                        },
                        new
                        {
                            Id = 27,
                            Category = "UserCourseStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2919),
                            Key = "Completed",
                            Value = "تکمیل شده"
                        },
                        new
                        {
                            Id = 28,
                            Category = "UserCourseStatus",
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(2920),
                            Key = "Cancelled",
                            Value = "لغو شده"
                        });
                });

            modelBuilder.Entity("MTA.Domain.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("MessageId");

                    b.HasIndex("TypeId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TicketId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("DurationUnitId")
                        .HasColumnType("int");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DurationUnitId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("MTA.Domain.Entities.PackageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingMessages")
                        .HasColumnType("int");

                    b.Property<int>("RemainingTickets")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageHistories");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3187),
                            Description = "Can manage user accounts",
                            Title = "ManageUsers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3189),
                            Description = "Can manage courses",
                            Title = "ManageCourses"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3190),
                            Description = "Can manage roles",
                            Title = "ManageRoles"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3191),
                            Description = "Can view analytics",
                            Title = "ViewAnalytics"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3192),
                            Description = "Can create course content",
                            Title = "CreateContent"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3193),
                            Description = "Can enroll in courses",
                            Title = "EnrollCourses"
                        });
                });

            modelBuilder.Entity("MTA.Domain.Entities.PermissionsRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionsRoles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.QuestionFAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("QuestionFAQs");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3119),
                            Title = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3120),
                            Title = "Coach"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 23, 7, 54, 47, 191, DateTimeKind.Utc).AddTicks(3121),
                            Title = "Student"
                        });
                });

            modelBuilder.Entity("MTA.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AccountId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int?>("PackageId1")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId1");

                    b.HasIndex("PackageId");

                    b.HasIndex("PackageId1");

                    b.HasIndex("StatusId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("MTA.Domain.Entities.UserCourseHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StatusId");

                    b.ToTable("UserCourseHistories");
                });

            modelBuilder.Entity("MTA.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("LevelId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Account", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Lookup", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Course", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Level", "Level")
                        .WithMany("Courses")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Lookup", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MTA.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Lesson", "Lesson")
                        .WithMany("MediaFiles")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MTA.Domain.Entities.Message", "Message")
                        .WithMany("MediaFiles")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MTA.Domain.Entities.Lookup", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Message");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Message", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", null)
                        .WithMany("Messages")
                        .HasForeignKey("AccountId");

                    b.HasOne("MTA.Domain.Entities.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Package", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Lookup", "DurationUnit")
                        .WithMany()
                        .HasForeignKey("DurationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DurationUnit");
                });

            modelBuilder.Entity("MTA.Domain.Entities.PackageHistory", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", "Account")
                        .WithMany("PackageHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Package", "Package")
                        .WithMany("PackageHistories")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("MTA.Domain.Entities.PermissionsRole", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Permission", "Permission")
                        .WithMany("PermissionsRoles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MTA.Domain.Entities.QuestionFAQ", b =>
                {
                    b.HasOne("MTA.Domain.Entities.FAQCategory", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Account", null)
                        .WithMany("Tickets")
                        .HasForeignKey("AccountId1");

                    b.HasOne("MTA.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Package", null)
                        .WithMany("Tickets")
                        .HasForeignKey("PackageId1");

                    b.HasOne("MTA.Domain.Entities.Lookup", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Package");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MTA.Domain.Entities.UserCourseHistory", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", "Account")
                        .WithMany("UserCourseHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Course", "Course")
                        .WithMany("UserCourseHistory")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Lookup", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Course");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MTA.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", "Account")
                        .WithOne("UserProfile")
                        .HasForeignKey("MTA.Domain.Entities.UserProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Level", null)
                        .WithMany("Profiles")
                        .HasForeignKey("LevelId");

                    b.HasOne("MTA.Domain.Entities.Level", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("SkillLevel");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Account", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("PackageHistory");

                    b.Navigation("Tickets");

                    b.Navigation("UserCourseHistory");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Course", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("UserCourseHistory");
                });

            modelBuilder.Entity("MTA.Domain.Entities.FAQCategory", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Level", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Message", b =>
                {
                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Package", b =>
                {
                    b.Navigation("PackageHistories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Permission", b =>
                {
                    b.Navigation("PermissionsRoles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
