// <auto-generated />
using System;
using MTA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTA.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTA.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageIcon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Poster")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("StatusId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MTA.Domain.Entities.FAQCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FAQCategories");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5840),
                            Title = "Beginner",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5842),
                            Title = "Intermediate",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5843),
                            Title = "Advanced",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5843),
                            Title = "Professional",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MTA.Domain.Entities.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Key")
                        .IsUnique();

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "AccountStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5536),
                            Key = "Active",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "فعال"
                        },
                        new
                        {
                            Id = 2,
                            Category = "AccountStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5540),
                            Key = "Inactive",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "غیرفعال"
                        },
                        new
                        {
                            Id = 3,
                            Category = "AccountStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5541),
                            Key = "Suspended",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "مسدود"
                        },
                        new
                        {
                            Id = 4,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5542),
                            Key = "Draft",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "پیش‌نویس"
                        },
                        new
                        {
                            Id = 5,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5543),
                            Key = "Published",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "منتشر شده"
                        },
                        new
                        {
                            Id = 6,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5544),
                            Key = "Archived",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "بایگانی"
                        },
                        new
                        {
                            Id = 7,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5545),
                            Key = "Suspended",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "معلق"
                        },
                        new
                        {
                            Id = 8,
                            Category = "CourseStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5545),
                            Key = "Retired",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "منقضی شده"
                        },
                        new
                        {
                            Id = 9,
                            Category = "MediaType",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5546),
                            Key = "Video",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "ویدئو"
                        },
                        new
                        {
                            Id = 10,
                            Category = "MediaType",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5547),
                            Key = "Document",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "سند"
                        },
                        new
                        {
                            Id = 11,
                            Category = "MediaType",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5548),
                            Key = "Image",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "تصویر"
                        },
                        new
                        {
                            Id = 12,
                            Category = "MediaType",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5548),
                            Key = "Audio",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "صوت"
                        },
                        new
                        {
                            Id = 13,
                            Category = "DurationUnit",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5549),
                            Key = "Day",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "روز"
                        },
                        new
                        {
                            Id = 14,
                            Category = "DurationUnit",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5550),
                            Key = "Week",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "هفته"
                        },
                        new
                        {
                            Id = 15,
                            Category = "DurationUnit",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5551),
                            Key = "Month",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "ماه"
                        },
                        new
                        {
                            Id = 16,
                            Category = "FAQCategory",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5551),
                            Key = "General",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "عمومی"
                        },
                        new
                        {
                            Id = 17,
                            Category = "FAQCategory",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5552),
                            Key = "Payment",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "پرداخت"
                        },
                        new
                        {
                            Id = 18,
                            Category = "FAQCategory",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5553),
                            Key = "Technical",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "فنی"
                        },
                        new
                        {
                            Id = 19,
                            Category = "FAQCategory",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5554),
                            Key = "Course",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "دوره‌ها"
                        },
                        new
                        {
                            Id = 20,
                            Category = "TicketStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5555),
                            Key = "Open",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "باز"
                        },
                        new
                        {
                            Id = 21,
                            Category = "TicketStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5555),
                            Key = "Pending",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "در انتظار"
                        },
                        new
                        {
                            Id = 22,
                            Category = "TicketStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5556),
                            Key = "Closed",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "بسته شده"
                        },
                        new
                        {
                            Id = 23,
                            Category = "PackageStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5557),
                            Key = "Active",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "فعال"
                        },
                        new
                        {
                            Id = 24,
                            Category = "PackageStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5558),
                            Key = "Expired",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "منقضی"
                        },
                        new
                        {
                            Id = 25,
                            Category = "PackageStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5558),
                            Key = "Pending",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "در انتظار"
                        },
                        new
                        {
                            Id = 26,
                            Category = "UserCourseStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5559),
                            Key = "Active",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "فعال"
                        },
                        new
                        {
                            Id = 27,
                            Category = "UserCourseStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5560),
                            Key = "Completed",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "تکمیل شده"
                        },
                        new
                        {
                            Id = 28,
                            Category = "UserCourseStatus",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5561),
                            Key = "Cancelled",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "لغو شده"
                        },
                        new
                        {
                            Id = 100,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5562),
                            Key = "RespectOthers",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "کاربران باید با احترام با یکدیگر رفتار کنند"
                        },
                        new
                        {
                            Id = 101,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5562),
                            Key = "NoSpam",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "ارسال پیام‌های تبلیغاتی یا اسپم مجاز نیست"
                        },
                        new
                        {
                            Id = 102,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5563),
                            Key = "FairPlay",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "رعایت اصول بازی جوانمردانه الزامی است"
                        },
                        new
                        {
                            Id = 103,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5564),
                            Key = "ProperContent",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "انتشار محتوای نامناسب یا توهین‌آمیز ممنوع است"
                        },
                        new
                        {
                            Id = 104,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5565),
                            Key = "FollowCoach",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "پیروی از دستورالعمل‌های مربی در طول تمرینات ضروری است"
                        },
                        new
                        {
                            Id = 105,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5565),
                            Key = "NoCheating",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "هرگونه تقلب یا رفتار غیر ورزشی ممنوع است"
                        },
                        new
                        {
                            Id = 106,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5566),
                            Key = "EquipmentCare",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "رعایت اصول نگهداری و مراقبت از تجهیزات الزامی است"
                        },
                        new
                        {
                            Id = 107,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5567),
                            Key = "Attendance",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "حضور به موقع در کلاس‌ها ضروری است"
                        },
                        new
                        {
                            Id = 108,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5568),
                            Key = "NoSmoking",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "سیگار کشیدن در محوطه آکادمی ممنوع است"
                        },
                        new
                        {
                            Id = 109,
                            Category = "SiteRule",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5568),
                            Key = "RespectFacilities",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "رعایت نظافت و احترام به امکانات آکادمی الزامی است"
                        },
                        new
                        {
                            Id = 200,
                            Category = "MediaPlacement",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5569),
                            Key = "WelcomeVideo",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "ویدئوی خوشامدگویی"
                        },
                        new
                        {
                            Id = 201,
                            Category = "MediaPlacement",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5570),
                            Key = "PromoVideo",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "ویدئوی تبلیغاتی"
                        },
                        new
                        {
                            Id = 202,
                            Category = "MediaPlacement",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5571),
                            Key = "SliderVideo",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "ویدئو اسلایدر"
                        },
                        new
                        {
                            Id = 203,
                            Category = "MediaPlacement",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5571),
                            Key = "TrainingPage",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "ویدئو صفحه آموزش"
                        },
                        new
                        {
                            Id = 204,
                            Category = "MediaPlacement",
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5572),
                            Key = "CoursePage",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "ویدئو صفحه دوره"
                        });
                });

            modelBuilder.Entity("MTA.Domain.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<int?>("PlacementId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("MessageId");

                    b.HasIndex("PlacementId");

                    b.HasIndex("TypeId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TicketId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("DurationUnitId")
                        .HasColumnType("int");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DurationUnitId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("MTA.Domain.Entities.PackageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingMessages")
                        .HasColumnType("int");

                    b.Property<int>("RemainingTickets")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageHistories");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5868),
                            Description = "Can manage user accounts",
                            Title = "ManageUsers",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5870),
                            Description = "Can manage courses",
                            Title = "ManageCourses",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5871),
                            Description = "Can manage roles",
                            Title = "ManageRoles",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5872),
                            Description = "Can view analytics",
                            Title = "ViewAnalytics",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5873),
                            Description = "Can create course content",
                            Title = "CreateContent",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5874),
                            Description = "Can enroll in courses",
                            Title = "EnrollCourses",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MTA.Domain.Entities.PermissionsRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionsRoles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.QuestionFAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("QuestionFAQs");
                });

            modelBuilder.Entity("MTA.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5801),
                            Title = "Admin",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5803),
                            Title = "Coach",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 9, 11, 12, 58, 571, DateTimeKind.Utc).AddTicks(5804),
                            Title = "Student",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MTA.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AccountId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int?>("PackageId1")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId1");

                    b.HasIndex("PackageId");

                    b.HasIndex("PackageId1");

                    b.HasIndex("StatusId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("MTA.Domain.Entities.UserCourseHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StatusId");

                    b.ToTable("UserCourseHistories");
                });

            modelBuilder.Entity("MTA.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HealthCondition")
                        .HasColumnType("bit");

                    b.Property<string>("HealthDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("LevelId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.VideoContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoContents");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Account", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Lookup", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Course", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Level", "Level")
                        .WithMany("Courses")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Lookup", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MTA.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Lesson", "Lesson")
                        .WithMany("MediaFiles")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MTA.Domain.Entities.Message", "Message")
                        .WithMany("MediaFiles")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MTA.Domain.Entities.Lookup", "Placement")
                        .WithMany()
                        .HasForeignKey("PlacementId");

                    b.HasOne("MTA.Domain.Entities.Lookup", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Message");

                    b.Navigation("Placement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Message", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", null)
                        .WithMany("Messages")
                        .HasForeignKey("AccountId");

                    b.HasOne("MTA.Domain.Entities.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Package", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Lookup", "DurationUnit")
                        .WithMany()
                        .HasForeignKey("DurationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DurationUnit");
                });

            modelBuilder.Entity("MTA.Domain.Entities.PackageHistory", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", "Account")
                        .WithMany("PackageHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Package", "Package")
                        .WithMany("PackageHistories")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("MTA.Domain.Entities.PermissionsRole", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Permission", "Permission")
                        .WithMany("PermissionsRoles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MTA.Domain.Entities.QuestionFAQ", b =>
                {
                    b.HasOne("MTA.Domain.Entities.FAQCategory", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MTA.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Account", null)
                        .WithMany("Tickets")
                        .HasForeignKey("AccountId1");

                    b.HasOne("MTA.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Package", null)
                        .WithMany("Tickets")
                        .HasForeignKey("PackageId1");

                    b.HasOne("MTA.Domain.Entities.Lookup", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Package");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MTA.Domain.Entities.UserCourseHistory", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", "Account")
                        .WithMany("UserCourseHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Course", "Course")
                        .WithMany("UserCourseHistory")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Lookup", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Course");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MTA.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("MTA.Domain.Entities.Account", "Account")
                        .WithOne("UserProfile")
                        .HasForeignKey("MTA.Domain.Entities.UserProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTA.Domain.Entities.Level", null)
                        .WithMany("Profiles")
                        .HasForeignKey("LevelId");

                    b.HasOne("MTA.Domain.Entities.Level", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("SkillLevel");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Account", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("PackageHistory");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Tickets");

                    b.Navigation("UserCourseHistory");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Course", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("UserCourseHistory");
                });

            modelBuilder.Entity("MTA.Domain.Entities.FAQCategory", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Level", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Message", b =>
                {
                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Package", b =>
                {
                    b.Navigation("PackageHistories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Permission", b =>
                {
                    b.Navigation("PermissionsRoles");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MTA.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
